name: "🐛Bug: SQL Comparison Example"
description: Parts or complete SQL queries to not lead to the intended results.
labels: [bug]
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to fill out this bug report.
  validations:
      required: true
      
- type: dropdown
  attributes:
    label: Which database are you using?
    multiple: true
    options:
      - dbiu.bahn
      - dbiu.bayern
      - dbiu.bundestag
      - dbiu.bundestag_einfach
      - dbiu.film_fernsehen
      - dbiu.haushaltsausstattung
      - dbiu.straftaten
      - dbiu.straftaten_einfach
      - dbiu.kunstsammlung
      - dbiu.ladepunkte
      - dbiu.laenderspiele
      - dbiu.lebensmittel
      - dbiu.schulstatistik
      - dbiu.studierende
      - dbiu.unfallstatistik
      - dbiu.videospiele_einfach
      - dbiu.videospiele
      - dbiu.wetterdaten
      - Other (please specify in additional context)
  validations:
    required: true
- type: textarea
  id: qA
  attributes:
    label: SQL Query 1
    placeholder: SELECT id,amount FROM TableA
    render: sql
  validations:
      required: true
- type: textarea
  id: aB
  attributes:
    label: SQL Query 2
    placeholder: SELECT amount,id FROM TableA
    render: sql
  validations:
      required: true
- type: checkboxes
  options:
    - label: Overall
    - label: Columns
    - label: Tables
  attributes:
    label: Which aspects of the queries should be equal?
  validations:
      required: true
  
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.

